
-- 1.4.3 
-- * using ib_util.ib_util_malloc library
-- * Fix all functions: return by CSTRING free_it and size


-- 1.1.4
DECLARE EXTERNAL FUNCTION CryptSha1String
CSTRING(32765)
RETURNS CSTRING(41) FREE_IT
ENTRY_POINT 'CryptSha1String' MODULE_NAME 'afucrypt';


DECLARE EXTERNAL FUNCTION CryptSha1BLOB
BLOB
RETURNS CSTRING(41) FREE_IT
ENTRY_POINT 'CryptSha1BLOB' MODULE_NAME 'afucrypt';


-- 1.1.3

DECLARE EXTERNAL FUNCTION CryptSha1File
CSTRING(2000)
RETURNS CSTRING(41) FREE_IT
ENTRY_POINT 'CryptSha1File' MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptMD5
CSTRING(32765)
RETURNS CSTRING(33) FREE_IT
ENTRY_POINT 'CryptMD5' MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptMD5Blob
Blob
RETURNS CSTRING(33) FREE_IT
ENTRY_POINT 'CryptMD5Blob' MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptMD5File
CSTRING(2000)
RETURNS CSTRING(33) FREE_IT
ENTRY_POINT 'CryptMD5File' MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptCRC32
CSTRING(32765)
RETURNS CSTRING(9) FREE_IT
ENTRY_POINT 'CryptCRC32'
MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptCRC32Blob
Blob
RETURNS CSTRING(9) FREE_IT
ENTRY_POINT 'CryptCRC32Blob'
MODULE_NAME 'afucrypt';

DECLARE EXTERNAL FUNCTION CryptCRC32File
CSTRING(2000)
RETURNS CSTRING(9) FREE_IT
ENTRY_POINT 'CryptCRC32File' MODULE_NAME 'afucrypt';
