-- 1.4.3 
--  * using ib_util.ib_util_malloc library
--  * fix some functions: returns value with free_it. FSFindRecName
--  * Type handle of object: integer -> bigint for x64_86 build

DECLARE EXTERNAL FUNCTION FSFileExists
CSTRING(1024)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFileExists' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFileToBLob
CSTRING(1024),Blob
RETURNS PARAMETER 2
ENTRY_POINT 'FSFileToBLob' MODULE_NAME 'afufile';

DECLARE EXTERNAL FUNCTION FSBlobToFile
Blob,CSTRING(1024)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSBlobToFile' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFileDelete
CSTRING(1024)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFileDelete' MODULE_NAME 'afufile';


--1.1.3
DECLARE EXTERNAL FUNCTION FSFindFirst
CSTRING(1024),INTEGER
RETURNS BIGINT BY VALUE
ENTRY_POINT 'FSFindFirst' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFindRecName
BIGINT
RETURNS CSTRING(1024) FREE_IT
ENTRY_POINT 'FSFindRecName' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFindNext
BIGINT  
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFindNext' MODULE_NAME 'afufile';

 
DECLARE EXTERNAL FUNCTION FSFindRecAttr
BIGINT  
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFindRecAttr' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFindRecCheckAttr
BIGINT ,INTEGER 
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFindRecCheckAttr' MODULE_NAME 'afufile';


DECLARE EXTERNAL FUNCTION FSFindClose
BIGINT  
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSFindClose' MODULE_NAME 'afufile';


-- 1.2.5
DECLARE EXTERNAL FUNCTION FSForceDirectories
CSTRING(1024)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'FSForceDirectories' MODULE_NAME 'afufile';

-- 1.2.6
DECLARE EXTERNAL FUNCTION FSFileCopy
CSTRING(1024),CSTRING(1024),INTEGER
RETURNS  INTEGER BY VALUE
ENTRY_POINT 'FSFileCopy' MODULE_NAME 'afufile';
