-- 1.4.3
-- * using ib_util.ib_util_malloc library
-- * Fix all functions: return by CSTRING free_it and size

DECLARE EXTERNAL FUNCTION CREATEZIP
RETURNS BIGINT BY VALUE
ENTRY_POINT 'CreateZIP' MODULE_NAME 'afuzip';



DECLARE EXTERNAL FUNCTION SetArhiveFileZIP
    BIGINT,CSTRING(255)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'SetArhiveFileZIP' MODULE_NAME 'afuzip';




DECLARE EXTERNAL FUNCTION AddSpecZIP
    BIGINT,CSTRING(255)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'AddSpecZIP' MODULE_NAME 'afuzip';



DECLARE EXTERNAL FUNCTION ClearSpecZIP
    BIGINT
RETURNS INTEGER BY VALUE
ENTRY_POINT 'ClearSpecZIP' MODULE_NAME 'afuzip';

DECLARE EXTERNAL FUNCTION SetRecurseDirZIP
    BIGINT, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT 'SetRecurseDirZIP' MODULE_NAME 'afuzip';



DECLARE EXTERNAL FUNCTION CompressZIP
    BIGINT
RETURNS INTEGER BY VALUE
ENTRY_POINT 'CompressZIP' MODULE_NAME 'afuzip';

DECLARE EXTERNAL FUNCTION SetExtractDirZIP
    BIGINT,CSTRING(255)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'SetExtractDirZIP' MODULE_NAME 'afuzip';

DECLARE EXTERNAL FUNCTION CreateUnZIP
RETURNS BIGINT BY VALUE
ENTRY_POINT 'CreateUnZIP' MODULE_NAME 'afuzip';


DECLARE EXTERNAL FUNCTION ExtractZIP
    BIGINT
RETURNS INTEGER BY VALUE
ENTRY_POINT 'ExtractZIP' MODULE_NAME 'afuzip';
