DROP EXTERNAL FUNCTION GetLastErrorObj;
DROP EXTERNAL FUNCTION MsgLastErrorObj;
DROP EXTERNAL FUNCTION WasErrorObj;
DROP EXTERNAL FUNCTION WasErrorIsExceptionObj;
DROP EXTERNAL FUNCTION SetMsgErrorExceptionObj;
DROP EXTERNAL FUNCTION FreeAFObject;
DROP EXCEPTION EXCEPTION_AFUDF;
DROP EXTERNAL FUNCTION DelCharsFromBlob;
--1.3.1
DROP EXTERNAL FUNCTION VersionAFUDF;
DROP EXTERNAL FUNCTION VersionExAFUDF;
DROP EXTERNAL FUNCTION GetTypeOS;

