DROP EXTERNAL FUNCTION FSFileExists; 
DROP EXTERNAL FUNCTION FSFileToBLob;
DROP EXTERNAL FUNCTION FSBlobToFile;
DROP EXTERNAL FUNCTION FSFileDelete;
--???
DROP EXTERNAL FUNCTION FSForceDirectories;

DROP EXTERNAL FUNCTION FSFileCopy;
